# Generated by Django 2.2.5 on 2019-09-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('capture_time', models.CharField(max_length=200)),
                ('capture_location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
