# Generated by Django 2.2.5 on 2019-09-27 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeAttendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='capture_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeAttendance.TerminalDetails'),
        ),
    ]
