# Generated by Django 2.2.5 on 2019-09-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeAttendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='capture_location',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
