# Generated by Django 2.2.5 on 2019-09-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeAttendance', '0002_employeeattendance_capture_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='capture_location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
