# Generated by Django 2.2.5 on 2019-09-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeAttendance', '0003_auto_20190910_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='capture_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
