# Generated by Django 2.2.5 on 2019-09-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeAttendance', '0005_auto_20190910_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('Gender', models.IntegerField()),
                ('CustomizeID', models.IntegerField(unique=True)),
            ],
        ),
    ]
