# Generated by Django 2.2.5 on 2019-09-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeAttendance', '0006_employeedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='img_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
