# Generated by Django 2.2.5 on 2019-09-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeAttendance', '0007_employeedetail_img_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='CustomizeID',
            field=models.IntegerField(),
        ),
    ]
