# Generated by Django 2.2.5 on 2019-09-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeAttendance', '0009_terminaldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='branch',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='department',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
